//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bloatbox.Locales {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bloatbox.Locales.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add selected &gt; ähnelt.
        /// </summary>
        internal static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add all &gt;&gt; ähnelt.
        /// </summary>
        internal static string BtnAddAll {
            get {
                return ResourceManager.GetString("BtnAddAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt; Remove selected ähnelt.
        /// </summary>
        internal static string BtnRemove {
            get {
                return ResourceManager.GetString("BtnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;&lt; Remove all ähnelt.
        /// </summary>
        internal static string BtnRemoveAll {
            get {
                return ResourceManager.GetString("BtnRemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uninstall ähnelt.
        /// </summary>
        internal static string BtnRunUninstaller {
            get {
                return ResourceManager.GetString("BtnRunUninstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show system apps ähnelt.
        /// </summary>
        internal static string ChkShowUWPSystem {
            get {
                return ResourceManager.GetString("ChkShowUWPSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///
        ///Remove Bloatwares from Windows 10.
        ///
        ///This project was intended as an extension for github.com/builtbybel/privatezilla
        ///
        ///All infos and credits about this project on
        ///\tgithub.com/builtbybel/bloatbox
        ///
        ///You can also reach out to me on
        ///\ttwitter.com/builtbybel
        ///
        ///(C) 2021, Builtbybel ähnelt.
        /// </summary>
        internal static string infoApp {
            get {
                return ResourceManager.GetString("infoApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This will download the PowerShell based Community version &quot;Windows10Debloater.ps1\n\nThis is a interactive script with prompts which runs the following functions:\n- Debloat (a list of Bloatware that is removed can be viewed on the authors GitHub repository)\n- Removes registry keys leftover that are associated with the bloatware apps\n- Protect privacy by stopping some telemetry functions, stops Cortana from being used as your Search Index, disables unneccessary scheduled tasks, and more\n- Stop-EdgePDF\n\ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string infoPS {
            get {
                return ResourceManager.GetString("infoPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No apps to uninstall! ähnelt.
        /// </summary>
        internal static string infoUninstallNull {
            get {
                return ResourceManager.GetString("infoUninstallNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apps &amp;&amp; Features ähnelt.
        /// </summary>
        internal static string LblHeader {
            get {
                return ResourceManager.GetString("LblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apps ähnelt.
        /// </summary>
        internal static string LblInstalledCount {
            get {
                return ResourceManager.GetString("LblInstalledCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string LblLeftAppName {
            get {
                return ResourceManager.GetString("LblLeftAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        internal static string LblRemoveCount {
            get {
                return ResourceManager.GetString("LblRemoveCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string LblRightAppName {
            get {
                return ResourceManager.GetString("LblRightAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move the apps you want to uninstall here. ähnelt.
        /// </summary>
        internal static string LblRightInfo {
            get {
                return ResourceManager.GetString("LblRightInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Optional features (download the Community version) ähnelt.
        /// </summary>
        internal static string LnkHeader {
            get {
                return ResourceManager.GetString("LnkHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start fresh if your Windows 10 is loaded with bloatware ähnelt.
        /// </summary>
        internal static string LnkStartFresh {
            get {
                return ResourceManager.GetString("LnkStartFresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check for updates ähnelt.
        /// </summary>
        internal static string menuCheckRelease {
            get {
                return ResourceManager.GetString("menuCheckRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        internal static string menuInfoApp {
            get {
                return ResourceManager.GetString("menuInfoApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visit Marketplace ähnelt.
        /// </summary>
        internal static string menuMarketplace {
            get {
                return ResourceManager.GetString("menuMarketplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add more features... ähnelt.
        /// </summary>
        internal static string menuPS {
            get {
                return ResourceManager.GetString("menuPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die github/bloatbox ähnelt.
        /// </summary>
        internal static string menuRepository {
            get {
                return ResourceManager.GetString("menuRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to run this script? ähnelt.
        /// </summary>
        internal static string msgDoPS {
            get {
                return ResourceManager.GetString("msgDoPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Be picky about which System applications to uninstall.\n\nYou can uninstall most of the built-in apps, even ones that don&apos;t normally offer an &quot;Uninstall&quot; option.\n\nNote, however, Bloatbox won&apos;t allow you to remove a few of the most important built-in apps, like Microsoft Edge, .NET framework, UI.Xaml etc. as these apps are needed for the Windows 10 &quot;Experience&quot; and for other programs. If you try, you’ll see an error message saying the removal failed. ähnelt.
        /// </summary>
        internal static string msgShowUWPSystem {
            get {
                return ResourceManager.GetString("msgShowUWPSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This will add all the annoying bloatware apps, pre-installed on Windows 10 including some apps your PC manufacturer included to the removal list.\r\n\nMost of these apps are garbage, but if you find important stuff on the list just remove it from the right box before hitting &quot;Uninstall&quot;. ähnelt.
        /// </summary>
        internal static string msgStartFresh {
            get {
                return ResourceManager.GetString("msgStartFresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disclaimer ähnelt.
        /// </summary>
        internal static string msgWarning {
            get {
                return ResourceManager.GetString("msgWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are using an unoffical version of Bloatbox ähnelt.
        /// </summary>
        internal static string releaseUnofficial {
            get {
                return ResourceManager.GetString("releaseUnofficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is a new version available ähnelt.
        /// </summary>
        internal static string releaseUpdateAvailable {
            get {
                return ResourceManager.GetString("releaseUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \n\nDo you want to open the @github/releases page? ähnelt.
        /// </summary>
        internal static string releaseUpdateAvailableURL {
            get {
                return ResourceManager.GetString("releaseUpdateAvailableURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \n\nYour are using version ähnelt.
        /// </summary>
        internal static string releaseUpdateYourVersion {
            get {
                return ResourceManager.GetString("releaseUpdateYourVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are currently no updates available. ähnelt.
        /// </summary>
        internal static string releaseUpToDate {
            get {
                return ResourceManager.GetString("releaseUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Removing ähnelt.
        /// </summary>
        internal static string statusDoUninstall {
            get {
                return ResourceManager.GetString("statusDoUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to remove: ähnelt.
        /// </summary>
        internal static string statusFailedRemove {
            get {
                return ResourceManager.GetString("statusFailedRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully removed: ähnelt.
        /// </summary>
        internal static string statusSuccessRemove {
            get {
                return ResourceManager.GetString("statusSuccessRemove", resourceCulture);
            }
        }
    }
}
